---
name: "Setup python venv with uv"
description: "Common setup steps"
runs:
  using: "composite"
  steps:
    # checkout (has to be repeated in downstream workflow jobs)
    - name: Checkout
      uses: actions/checkout@v5
    # python
    - name: "Set up Python"
      uses: actions/setup-python@v6
      with:
        python-version-file: ".python-version"
    # uv
    - name: "Setup uv with caching enabled"
      uses: astral-sh/setup-uv@v5
      with:
        enable-cache: true
        version: "0.9.8"
    - name: Install the project
      shell: sh
      run: uv sync --locked --all-extras --dev
      env:
        UV_SYSTEM_PYTHON: 1
